#!/bin/bash
# ==============================================================================
# LaTeX Compilation Script
# Forecasting International Migration to North Dakota: A Multi-Method Analysis
# ==============================================================================
# This script compiles the LaTeX document to PDF using pdflatex and bibtex.
#
# Requirements:
#   - TeX Live or similar LaTeX distribution with pdflatex
#   - bibtex for bibliography processing
#   - Required LaTeX packages (see preamble.tex for full list):
#     - amsmath, amssymb, amsthm (mathematics)
#     - graphicx, float, subcaption (figures)
#     - booktabs, array, multirow, threeparttable, tabularx (tables)
#     - natbib (citations)
#     - hyperref (hyperlinks)
#     - enumitem, xcolor, fancyhdr, titlesec (formatting)
#     - geometry, setspace (page layout)
#
# Usage:
#   ./compile.sh [--clean] [--quick] [--output <path>] [--no-copy]
#
# Options:
#   --clean      Remove auxiliary files before compilation
#   --quick      Run only pdflatex once (skip bibtex and multiple passes)
#   --output     Copy compiled PDF to the specified path
#   --no-copy    Skip copying the PDF to the output directory
#
# Output:
#   main.pdf   Compiled PDF document
#   output/article_draft.pdf   Copy for distribution
# ==============================================================================

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# TeX Live writes cache/fonts under user-level TEXMFVAR by default (often under `$HOME`),
# which may be outside the workspace sandbox. Redirect these paths into the repo so
# compilation succeeds in sandboxed environments.
export TEXMFVAR="${SCRIPT_DIR}/.texmf-var"
export TEXMFCONFIG="${SCRIPT_DIR}/.texmf-config"
mkdir -p "$TEXMFVAR" "$TEXMFCONFIG"

# Parse arguments
CLEAN=false
QUICK=false
COPY_OUTPUT=true
OUTPUT_PATH=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --clean)
            CLEAN=true
            shift
            ;;
        --quick)
            QUICK=true
            shift
            ;;
        --output)
            if [ -z "$2" ]; then
                echo "ERROR: --output requires a path"
                exit 1
            fi
            OUTPUT_PATH="$2"
            shift 2
            ;;
        --no-copy)
            COPY_OUTPUT=false
            shift
            ;;
        *)
            echo "ERROR: Unknown option: $1"
            exit 1
            ;;
    esac
done

# Clean auxiliary files if requested
if [ "$CLEAN" = true ]; then
    echo "Cleaning auxiliary files..."
    rm -f main.aux main.bbl main.blg main.log main.out main.toc main.lof main.lot
fi

# Check for pdflatex
if ! command -v pdflatex &> /dev/null; then
    echo "ERROR: pdflatex not found. Please install a LaTeX distribution."
    echo ""
    echo "Installation options:"
    echo "  Ubuntu/Debian: sudo apt-get install texlive-full"
    echo "  Fedora/RHEL:   sudo dnf install texlive-scheme-full"
    echo "  macOS:         brew install --cask mactex"
    echo "  Windows:       Download MiKTeX from https://miktex.org/"
    echo ""
    echo "Alternatively, upload the files to Overleaf (https://www.overleaf.com/)"
    exit 1
fi

echo "============================================================"
echo "Compiling: Forecasting International Migration to North Dakota"
echo "============================================================"

# Generate derived stats macros (best-effort; compilation should not fail if unavailable).
if command -v uv &> /dev/null && [ -f "generate_derived_stats.py" ]; then
    echo ""
    echo "Generating derived stats (derived_stats.tex)..."
    uv run python generate_derived_stats.py || echo "WARNING: Failed to generate derived_stats.tex; using fallback macros."
fi

# Check for required appendix diagnostic figure (generated by regime-aware PEP runner).
if [ ! -f "figures/fig_app_pep_regime_diagnostic.png" ]; then
    echo ""
    echo "WARNING: Missing figures/fig_app_pep_regime_diagnostic.png"
    echo "  Generate it with:"
    echo "    uv run python ../run_pep_regime_modeling.py"
    echo "  (or run the full one-command build: build_versioned_artifacts.py --refresh)"
    echo ""
fi

if [ "$QUICK" = true ]; then
    echo "Running quick compilation (single pdflatex pass)..."
    pdflatex -interaction=nonstopmode main.tex
else
    echo "Pass 1: Running pdflatex..."
    pdflatex -interaction=nonstopmode main.tex

    echo ""
    echo "Running bibtex for bibliography..."
    bibtex main || echo "Warning: bibtex returned non-zero exit code"

    echo ""
    echo "Pass 2: Running pdflatex..."
    pdflatex -interaction=nonstopmode main.tex

    echo ""
    echo "Pass 3: Running pdflatex (final pass for references)..."
    pdflatex -interaction=nonstopmode main.tex
fi

# Check if PDF was created
if [ -f "main.pdf" ]; then
    echo ""
    echo "============================================================"
    echo "Compilation successful!"
    echo "============================================================"

    # Copy to output directory unless disabled
    if [ "$COPY_OUTPUT" = true ]; then
        if [ -n "$OUTPUT_PATH" ]; then
            mkdir -p "$(dirname "$OUTPUT_PATH")"
            cp main.pdf "$OUTPUT_PATH"
            echo "Copy: $OUTPUT_PATH"
            # Keep the standard draft copy in sync even when an explicit output path is used
            # (e.g., during versioned artifact builds).
            mkdir -p output
            cp main.pdf output/article_draft.pdf
            echo "Copy: $(pwd)/output/article_draft.pdf"
        else
            mkdir -p output
            cp main.pdf output/article_draft.pdf
            echo "Copy: $(pwd)/output/article_draft.pdf"
        fi
    fi
    echo "Output: $(pwd)/main.pdf"

    # Report PDF info
    if command -v pdfinfo &> /dev/null; then
        echo ""
        echo "PDF Information:"
        pdfinfo main.pdf | grep -E "^(Pages|File size):"
    fi
else
    echo ""
    echo "ERROR: Compilation failed. Check main.log for details."
    exit 1
fi
