"""Build the PUB-2026 marketing-handoff Word documents from locked sources.

These ``.docx`` files are the narrative half of the marketing handoff drop in
``docs/plans/2026-public-projection-release-handoff/marketing-ready/``. They were
previously hand-authored and went stale when the data artifacts were refreshed
to the locked-config production run (they kept pre-lock numbers and the retired
three-scenario framing). This script regenerates them from the single source of
truth so they can never silently drift again:

- Narrative copy  -> ``draft-public-pdf-copy.md`` (locked, ADR-065 baseline-only)
- Storyboard      -> ``pdf-content-outline.md``
- 2024 SDC notes  -> ``2024-sdc-pdf-review.md``
- Overview        -> ``marketing-ready/README.md``
- Methods companion -> ``how-these-projections-work.md`` (public explainer)
- Numbers table   -> the locked public CSV (``drafts/PUB-2026 Draft Public Dataset.csv``)

All numeric callouts therefore come from the corrected full-horizon production run
(``m2026r1`` / ``cfg-20260611-production-lock``; ADR-068 + 2026-06-16 survival-horizon
amendment; config sha256(16) ``a6e0bfbc2d70be85``).

IMPORTANT — not everything auto-refreshes. The **layout-numbers** doc and the workbook
derive their figures from the CSV, so they update automatically. The **narrative prose**
(``draft-public-pdf-copy.md``, ``how-these-projections-work.md``, and the README/storyboard) is
HAND-AUTHORED: this script re-renders it verbatim and does *not* update its numbers. So whenever
the locked run changes, the prose must be edited by hand. To catch a miss, ``main()`` runs
``_check_prose_sync()`` — it cross-checks the hand-authored figures (2055 total, trough
year/value, the declining-county count, the five county callouts, the top-three gains share, and
the 2024-comparison table values) against the locked CSV and prints a loud warning (or, with
``--strict``, exits non-zero) when they drift.

Usage:
    python scripts/exports/build_marketing_docx.py            # regenerate (warns on prose drift)
    python scripts/exports/build_marketing_docx.py --strict   # fail if the prose is out of sync

Rerun this whenever the locked markdown copy or the locked CSV changes. It is a
pre-publication handoff aid: numbers are final/locked; marketing still owns
layout, branding, accessibility, and the contact/download placeholder fill.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd
from docx import Document
from docx.shared import Pt, RGBColor
from docx.text.paragraph import Paragraph

HANDOFF_DIR = Path(__file__).resolve().parents[2] / "docs" / "plans" / "2026-public-projection-release-handoff"
MARKETING_DIR = HANDOFF_DIR / "marketing-ready"
LOCKED_CSV = MARKETING_DIR / "drafts" / "PUB-2026 Draft Public Dataset.csv"

RUN_TAG = (
    "m2026r1 / cfg-20260611-production-lock — ADR-068 corrected full-horizon run "
    "(2026-06-15 + 2026-06-16 survival-horizon amendment; config sha256(16) a6e0bfbc2d70be85)"
)
PREPUB_NOTE = (
    "Pre-publication marketing draft. Numbers are final/locked from the production run "
    f"{RUN_TAG}; this document is DRAFT only because public layout and release are pending, "
    "not because the data is provisional. Generated by scripts/exports/build_marketing_docx.py — "
    "do not hand-edit; rerun the generator instead."
)
KEY_YEARS = [2025, 2030, 2035, 2040, 2045, 2050, 2055]


# ---------------------------------------------------------------------------
# Minimal Markdown -> docx rendering (covers the subset our sources use:
# # / ## / ### headings, paragraphs, "- " bullets, **bold**, and | pipe | tables)
# ---------------------------------------------------------------------------


def _add_runs_with_bold(paragraph: Paragraph, text: str) -> None:
    for chunk in re.split(r"(\*\*.+?\*\*)", text):
        if not chunk:
            continue
        if chunk.startswith("**") and chunk.endswith("**"):
            run = paragraph.add_run(chunk[2:-2])
            run.bold = True
        else:
            paragraph.add_run(chunk)


def _add_pipe_table(doc: Document, header: list[str], rows: list[list[str]]) -> None:
    table = doc.add_table(rows=1, cols=len(header))
    table.style = "Light Grid Accent 1"
    for j, cell_text in enumerate(header):
        run = table.rows[0].cells[j].paragraphs[0].add_run(cell_text)
        run.bold = True
    for row in rows:
        cells = table.add_row().cells
        for j, cell_text in enumerate(row):
            _add_runs_with_bold(cells[j].paragraphs[0], cell_text)
    doc.add_paragraph()


def _render_markdown(doc: Document, md_text: str, *, skip_first_h1: bool = True) -> None:
    """Render a constrained Markdown subset into an existing Document."""
    lines = md_text.splitlines()
    i = 0
    seen_h1 = False
    bullet_pending = False
    while i < len(lines):
        line = lines[i].rstrip()
        # horizontal rules render as section breaks (blank), not literal dashes
        if line.strip() in ("---", "***", "___"):
            bullet_pending = False
            i += 1
            continue
        # blockquote banners/technical notes render as plain paragraphs
        if line.lstrip().startswith(">"):
            line = line.lstrip().lstrip(">").lstrip()
            if not line:
                i += 1
                continue
        # pipe table block
        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:|-]+\|?\s*$", lines[i + 1]):
            header = [c.strip() for c in line.strip("|").split("|")]
            i += 2
            rows: list[list[str]] = []
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            _add_pipe_table(doc, header, rows)
            bullet_pending = False
            continue
        if not line:
            bullet_pending = False
            i += 1
            continue
        if line.startswith("### "):
            doc.add_heading(line[4:].strip(), level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:].strip(), level=2)
        elif line.startswith("# "):
            if skip_first_h1 and not seen_h1:
                seen_h1 = True
                i += 1
                continue
            doc.add_heading(line[2:].strip(), level=1)
        elif line.lstrip().startswith("- ") or re.match(r"^\d+\.\s", line.lstrip()):
            text = re.sub(r"^(\s*-\s|\s*\d+\.\s)", "", line)
            para = doc.add_paragraph(style="List Bullet")
            _add_runs_with_bold(para, text)
            bullet_pending = True
        else:
            # continuation of a wrapped paragraph/bullet collapses to one space
            if bullet_pending:
                last = doc.paragraphs[-1]
                last.add_run(" ")
                _add_runs_with_bold(last, line.strip())
            else:
                para = doc.add_paragraph()
                _add_runs_with_bold(para, line.strip())
        i += 1


def _new_doc(title: str, subtitle: str | None = None) -> Document:
    doc = Document()
    doc.add_heading(title, level=0)
    banner = doc.add_paragraph()
    run = banner.add_run(PREPUB_NOTE)
    run.italic = True
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    if subtitle:
        sub = doc.add_paragraph()
        sub_run = sub.add_run(subtitle)
        sub_run.bold = True
    doc.add_paragraph()
    return doc


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Numbers doc (built from the locked CSV, not from markdown)
# ---------------------------------------------------------------------------


def _round_k(value: float) -> str:
    return f"{round(value, -3):,.0f}"


def _render_numbers(doc: Document) -> None:
    """Render the locked layout-numbers sections into an existing document."""
    df = pd.read_csv(LOCKED_CSV)

    doc.add_heading("Statewide baseline, key years", level=2)
    st = df[df.geography_level == "state"].sort_values("year").set_index("year")
    base = st.loc[2025, "total_population"]
    rows = []
    for y in KEY_YEARS:
        pop = st.loc[y, "total_population"]
        rows.append([str(y), _round_k(pop), f"{(pop / base - 1) * 100:+.1f}%"])
    trough_year = int(st["total_population"].idxmin())
    trough_pop = st.loc[trough_year, "total_population"]
    _add_pipe_table(doc, ["Year", "Population", "Change vs 2025"], rows)
    note = doc.add_paragraph()
    _add_runs_with_bold(
        note,
        f"**Trough:** about {_round_k(trough_pop)} around {trough_year} "
        "(the intended CBO front-loaded migration ramp), before steady recovery to 2055.",
    )

    doc.add_heading("Regional change, 2025 to 2055", level=2)
    reg = df[df.geography_level == "region"]
    if not reg.empty:
        piv = reg.pivot_table(index=["geography_name"], columns="year", values="total_population")
        rrows = []
        for name, r in piv.sort_values(2055, ascending=False).iterrows():
            rrows.append(
                [str(name), _round_k(r[2025]), _round_k(r[2055]), f"{(r[2055] / r[2025] - 1) * 100:+.1f}%"]
            )
        _add_pipe_table(doc, ["Region", "2025", "2055", "Change"], rrows)
    else:
        doc.add_paragraph("(Region rows not present in this CSV vintage.)")

    doc.add_heading("County concentration, 2025 to 2055", level=2)
    cty = df[df.geography_level == "county"]
    cpiv = cty.pivot_table(index=["geography_name"], columns="year", values="total_population")
    cpiv["pct"] = (cpiv[2055] / cpiv[2025] - 1) * 100
    declining = int((cpiv[2055] < cpiv[2025]).sum())
    summary = doc.add_paragraph()
    _add_runs_with_bold(
        summary,
        f"**{declining} of {len(cpiv)} counties** are projected to decline. Most statewide growth "
        "is concentrated in Cass (Fargo), Williams (Williston), and Burleigh (Bismarck).",
    )
    top = cpiv.sort_values("pct", ascending=False).head(6)
    bot = cpiv.sort_values("pct").head(6)
    doc.add_heading("Largest projected growth", level=3)
    _add_pipe_table(
        doc,
        ["County", "2025", "2055", "Change"],
        [[n, _round_k(r[2025]), _round_k(r[2055]), f"{r['pct']:+.1f}%"] for n, r in top.iterrows()],
    )
    doc.add_heading("Largest projected decline", level=3)
    _add_pipe_table(
        doc,
        ["County", "2025", "2055", "Change"],
        [[n, _round_k(r[2025]), _round_k(r[2055]), f"{r['pct']:+.1f}%"] for n, r in bot.iterrows()],
    )


def build_numbers_doc() -> Document:
    doc = _new_doc(
        "PUB-2026 Draft Numbers For Layout",
        "Rounded layout values from the locked Baseline (CBO-Adjusted) public run. "
        "Exact annual values live in the public CSV/workbook; the downloads are authoritative.",
    )
    _render_numbers(doc)
    return doc


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def build_all() -> list[Path]:
    written: list[Path] = []

    # 1. Public PDF copy
    doc = _new_doc("PUB-2026 Draft Public PDF Copy")
    _render_markdown(doc, _read(HANDOFF_DIR / "draft-public-pdf-copy.md"))
    out = MARKETING_DIR / "PUB-2026 Draft Public PDF Copy.docx"
    doc.save(out)
    written.append(out)

    # 2. Numbers for layout
    out = MARKETING_DIR / "PUB-2026 Draft Numbers For Layout.docx"
    build_numbers_doc().save(out)
    written.append(out)

    # 3. Storyboard
    doc = _new_doc("PUB-2026 PDF Report Storyboard")
    _render_markdown(doc, _read(HANDOFF_DIR / "pdf-content-outline.md"))
    out = MARKETING_DIR / "PUB-2026 PDF Report Storyboard.docx"
    doc.save(out)
    written.append(out)

    # 4. 2024 SDC reference notes
    doc = _new_doc("PUB-2026 2024 SDC Reference Notes")
    _render_markdown(doc, _read(HANDOFF_DIR / "2024-sdc-pdf-review.md"))
    out = MARKETING_DIR / "PUB-2026 2024 SDC Reference Notes.docx"
    doc.save(out)
    written.append(out)

    # 5. Handoff overview (folder README)
    doc = _new_doc("PUB-2026 Handoff Overview")
    _render_markdown(doc, _read(MARKETING_DIR / "README.md"))
    out = MARKETING_DIR / "PUB-2026 Handoff Overview.docx"
    doc.save(out)
    written.append(out)

    # 6. Public methods companion (explainer)
    doc = _new_doc(
        "PUB-2026 How These Projections Work",
        "Plain-language companion to the public report: how the cohort-component method "
        "works, what the baseline assumes, and how far to trust it. Link it from the report "
        "and the download page, or bind it in as a methods appendix.",
    )
    _render_markdown(doc, _read(HANDOFF_DIR / "how-these-projections-work.md"))
    out = MARKETING_DIR / "PUB-2026 How These Projections Work.docx"
    doc.save(out)
    written.append(out)

    # 7. Combined marketing handoff packet
    packet = _new_doc(
        "PUB-2026 Marketing Handoff Packet",
        "Combined packet: handoff overview, public PDF copy, report storyboard, "
        "numbers for layout, 2024 SDC reference notes, and the public methods companion.",
    )
    packet.add_heading("1. Handoff Overview", level=1)
    _render_markdown(packet, _read(MARKETING_DIR / "README.md"))
    packet.add_page_break()
    packet.add_heading("2. Draft Public PDF Copy", level=1)
    _render_markdown(packet, _read(HANDOFF_DIR / "draft-public-pdf-copy.md"))
    packet.add_page_break()
    packet.add_heading("3. PDF Report Storyboard", level=1)
    _render_markdown(packet, _read(HANDOFF_DIR / "pdf-content-outline.md"))
    packet.add_page_break()
    packet.add_heading("4. Draft Numbers For Layout", level=1)
    _render_numbers(packet)
    packet.add_page_break()
    packet.add_heading("5. 2024 SDC Reference Notes", level=1)
    _render_markdown(packet, _read(HANDOFF_DIR / "2024-sdc-pdf-review.md"))
    packet.add_page_break()
    packet.add_heading("6. How These Projections Work (public companion)", level=1)
    _render_markdown(packet, _read(HANDOFF_DIR / "how-these-projections-work.md"))
    out = MARKETING_DIR / "PUB-2026 Marketing Handoff Packet.docx"
    packet.save(out)
    written.append(out)

    return written


def _check_prose_sync() -> list[str]:
    """Flag hand-authored public prose that has drifted from the locked CSV.

    The narrative copy in ``draft-public-pdf-copy.md`` and the public explainer
    ``how-these-projections-work.md`` are written by hand and do NOT regenerate from data
    (only the layout-numbers doc and the workbook do). This catches the failure mode where
    the projection run changes but the prose callouts are not updated — e.g. the ADR-068
    corrections, where the data artifacts refreshed to 898,907 but the prose kept the
    pre-correction 787k/889k story, and the 2026-07-06 errata, where the declining-county
    count stayed at the pre-amendment 37 after the locked CSV moved to 36. Returns a list of
    issues (empty == in sync). The rounding convention here matches ``_round_k`` (nearest
    thousand, comma-formatted), which is the convention the prose uses, so the comparison is
    apples-to-apples.

    Tokens checked per file:
    - both: rounded 2055 state total, rounded trough population, trough year, and the
      declining-county count ("N of [the] 53").
    - PDF copy only: the five county callouts (rounded 2055 values for Cass, Williams,
      Burleigh, Ward, Grand Forks), the exact 2030/2040/2050 values in the 2024-edition
      comparison table, and the "three-quarters" top-3 gains phrasing (flagged if the
      computed share leaves the 75-85% band where that phrase is accurate).

    NOT machine-checked (re-verify by hand on every run change): median age (35 -> 40),
    the "about 91% of 2023-2025 net migration is international" share (both need production
    parquets, not the public CSV), and the 2018-vintage track-record figures
    (793,537 / 779,094 — quoted from the 2024 edition's Note of Caution).
    """
    issues: list[str] = []
    if not LOCKED_CSV.exists():
        return issues
    df = pd.read_csv(LOCKED_CSV)
    st = df.query("geography_level == 'state'").sort_values("year").set_index("year")
    total_2055 = _round_k(st.loc[2055, "total_population"])
    trough_year = int(st["total_population"].idxmin())
    trough_pop = _round_k(st.loc[trough_year, "total_population"])

    cty = df[df.geography_level == "county"]
    cpiv = cty.pivot_table(index="geography_name", columns="year", values="total_population")
    growth = cpiv[2055] - cpiv[2025]
    declining = int((growth < 0).sum())
    n_counties = len(cpiv)
    top3_share = growth.nlargest(3).sum() / growth[growth > 0].sum() * 100
    decline_re = re.compile(rf"\b{declining} of (?:the )?(?:North Dakota's )?{n_counties}\b")
    # exec-summary spelled-out form ("Thirty-six of North Dakota's 53")
    _units = [
        "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
        "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
        "seventeen", "eighteen", "nineteen",
    ]
    _tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
    spelled = (
        _units[declining]
        if declining < 20
        else _tens[declining // 10] + ("-" + _units[declining % 10] if declining % 10 else "")
    )
    spelled_re = re.compile(rf"\b{spelled} of\b", re.IGNORECASE)

    checks: list[tuple[Path, list[tuple[str, str]]]] = []

    pdf_tokens = [
        (f"2055 state total ({total_2055})", total_2055),
        (f"trough population ({trough_pop})", trough_pop),
        (f"trough year ({trough_year})", str(trough_year)),
    ]
    for county in ("Cass", "Williams", "Burleigh", "Ward", "Grand Forks"):
        names = [n for n in cpiv.index if str(n).startswith(county)]
        if names:
            val = _round_k(cpiv.loc[names[0], 2055])
            pdf_tokens.append((f"{county} 2055 callout ({val})", val))
    for year in (2030, 2040, 2050):
        exact = f"{st.loc[year, 'total_population']:,.0f}"
        pdf_tokens.append((f"2024-edition comparison value for {year} ({exact})", exact))
    checks.append((HANDOFF_DIR / "draft-public-pdf-copy.md", pdf_tokens))

    checks.append(
        (
            HANDOFF_DIR / "how-these-projections-work.md",
            [
                (f"2055 state total ({total_2055})", total_2055),
                (f"trough population ({trough_pop})", trough_pop),
                (f"trough year ({trough_year})", str(trough_year)),
            ],
        )
    )

    for path, tokens in checks:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for label, token in tokens:
            if token not in text:
                issues.append(f"{path.name} does not mention the current {label}")
        if not (decline_re.search(text) or spelled_re.search(text)):
            issues.append(
                f"{path.name} does not carry the current declining-county count "
                f"({declining} of {n_counties})"
            )
        if "three-quarters" in text and not (75.0 <= top3_share < 85.0):
            issues.append(
                f"{path.name} says 'three-quarters' but the computed top-3 share of gains "
                f"is {top3_share:.1f}% — rephrase or re-verify"
            )
    return issues


def main() -> None:
    issues = _check_prose_sync()
    written = build_all()
    print(f"Wrote {len(written)} marketing .docx files to {MARKETING_DIR}:")
    for path in written:
        print(f"  - {path.name}")
    print(f"\nAll numbers locked to {RUN_TAG}.")
    if issues:
        print("\n" + "=" * 72)
        print("⚠️  PUBLIC-PROSE SYNC WARNING — the hand-authored narrative may be STALE:")
        for issue in issues:
            print(f"   - {issue}")
        print(
            "   The prose does NOT auto-update from data. Edit "
            "docs/.../draft-public-pdf-copy.md and\n   how-these-projections-work.md "
            "against the locked CSV (final-run-metadata.md), then rerun\n   this generator."
        )
        print("=" * 72)
        if "--strict" in sys.argv:
            raise SystemExit(1)
    else:
        print("Public-prose sync check: OK (prose matches the locked CSV headline figures).")


if __name__ == "__main__":
    main()
